config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :members, only: [:show]

  resources :posts

  root 'feed#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!
  before_action :set_member, only: [:show]

  private

  def set_member
    @member = Member.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = current_member.posts.build
  end

  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Brawo! Dodałeś post.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit() end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post został zaktualizowany.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show() end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Usunięto post.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feed/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shelter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="mainheader" class="site-header">
      <div class="container">
        <nav class="navbar">
          <div class="menu">

            <ul>
              <% if member_signed_in?%>
                <li><%=link_to "Dodaj post", root_path %></li>
                <li><%=link_to "Profil", current_member %></li>
                <li><%=link_to "Wyloguj się", destroy_member_session_path, method: :delete %></li>
              <% else %>
                <li class="join"><%=link_to "Dołącz", new_member_registration_path %></li>
                <li class="login"><%= link_to "Zaloguj się", new_member_session_path %></li>
              <% end %>
            </ul>
         </div>
        </nav>
      </div>
    </header>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <div class="footer">
      <div class="footer-container">
        <p>Copyright © 2020 Shelter, Inc</p>
      </div>
    </div>
  </body>
</html>

app/views/members/show.html.erb
<%= @member.email %>

app/views/posts/index.html.erb
<h2>Post index</h2>